### ISSUE TITLE
Sprint 4: Create HLDD for the project

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#18]
Complete the [HLDD](https://docs.google.com/document/d/12WY0N-tc8HnmMoDPao-iJuTizYyqAsbTaEWsWWmYY2A/edit) with each new functionality/upgrade added to the Enabler application.

Use [this article](https://wiki.keitaro.com/en/engineering) for reference.

**Note:** This task is WIP and will be completed with the end of Sprint 4.

**Comment by JasminaPN** [comment]
Closing this ticket since we are moving this project on Plane Task Board.
