### ISSUE TITLE
Sprint 3: Enabler - setup init

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#53]
Set up init for the enabler app.

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)): 
_After doing some testing, once i try to do enabler setup init i get the follow error which says that i am missing kubectl but i have kubectl installed just in a diffrent dir._

[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ enabler setup init
-Downloading kubectl...
Traceback (most recent call last):
  File "/home/filip/.local/bin/enabler", line 33, in <module>
    sys.exit(load_entry_point('enabler', 'console_scripts', 'enabler')())
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/filip/Desktop/Projects/enabler/enabler/enabler/commands/cmd_setup.py", line 46, in init
    urllib.request.urlretrieve(kubectl_url, 'bin/kubectl')
  File "/usr/lib/python3.10/urllib/request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'bin/kubectl'
[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ which kubectl 
/usr/local/bin/kubectl

/etc/issue
Ubuntu 22.04.3 LTS \n \l

kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
**WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1**

enabler version
Enabler 0.1

**Comment by teodora-aleksovska** [comment]
ToDo: 
- [x] Additional check to verify if kubectl has been installed in different dir.

The result after running _enabler setup init_:

kubectl found at: /home/teodora/.asdf/shims/kubectl. Continuing with other dependencies...
Downloading helm...
helm downloaded!
Downloading istioctl...
istioctl downloaded!
Downloading kind...
kind downloaded!
Downloading skaffold...
skaffold downloaded!

All dependencies downloaded to bin/
IMPORTANT: Please add the path to your user profile to /home/teodora/.config/enabler/bin directory at the beginning of your PATH
$ echo export PATH=/home/teodora/.config/enabler/bin:$PATH >> ~/.profile
$ source ~/.profile

**Comment by gocemitevski** [comment]
@teodora-aleksovska there are multiple linting errors in the PR. We first need to resolve these so work can continue. Also, we should not have hard-coded URLs to the dependencies - this should be somehow configurable.

**Comment by Magi-Jakimovska** [comment]
Code optimization including removal of linting errors and replacing hard-coded url-s will be tracked here - #60.
@teodora-aleksovska, for task #53, please provide:

- estimated time of completion, and
- any blockers/dependencies.

cc: @gocemitevski

**Comment by teodora-aleksovska** [comment]
Please review this [PR](https://github.com/keitaroinc/enabler/pull/62)

**Comment by JasminaPN** [comment]
Closing since the MR was approved.
