### ISSUE TITLE
Sprint 3: Enabler - platform version

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#54]
Investigate errors why enabler platform version doesn't return anything on enabler fresh install.

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)):
_When you do a fresh install of enabler and try to use enabler platform version it doesn't return anything there should be some kind of an error most likely or some output._

[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ enabler platform version
[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ 
/etc/issue
Ubuntu 22.04.3 LTS \n \l

kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1

enabler version
Enabler 0.1

**Comment by teodora-aleksovska** [comment]
While debugging, I noticed that the submodules list is empty. This might be the reason why it doesn't return the version of the platform.

**Comment by JasminaPN** [comment]
It will be tested on a real project so we can verify it. 
It will be closed once tested.

**Comment by JasminaPN** [comment]
I will close this ticket and will open it as a separate task for Sprint 4.
We should decide on which project should be tested.
