### ISSUE TITLE
Sprint 3: Enabler - autocomplete

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#55]
Add auto-complete for all commands of enabler.

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)).

**Comment by teodora-aleksovska** [comment]
Please review this[ PR](https://github.com/keitaroinc/enabler/pull/69)

**Comment by JasminaPN** [comment]
Closing since the MR was approved.
