### ISSUE TITLE
Sprint 3: Enabler - setup metallb

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#57]
Investigate if the below testing results are actual error or expected behavior.

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)):

_When doing enabler setup metallb --kube-context kind this is without enabler setup init since my kubectl is installed in a different location so this could be a normal error._

[filip@Thinkpad enabler (⎈ |kind-kind:default)]$ enabler setup metallb --kube-context kind
Metallb not found. Installing...
Downloading metallb version ...
Repo update ...
Traceback (most recent call last):
  File "/home/filip/.local/bin/enabler", line 33, in <module>
    sys.exit(load_entry_point('enabler', 'console_scripts', 'enabler')())
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/filip/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/filip/Desktop/Projects/enabler/enabler/enabler/commands/cmd_setup.py", line 202, in metallb
    with open(yaml_file_path, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'enabler/metallb-crd.yaml'

/etc/issue
Ubuntu 22.04.3 LTS \n \l

kubectl version
Client Version: [version.Info](http://version.info/){Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: [version.Info](http://version.info/){Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1

enabler version
Enabler 0.1

**Comment by teodora-aleksovska** [comment]
The issue with metallb-crd.yaml file path is solved. 
When I  run enabler setup metallb --kube-context kind i get the follow error:

teodora@teodora-ThinkPad-T16-Gen-1:~/.config/enabler$ enabler setup metallb --kube-context kind
Metallb not found. Installing...
Downloading metallb version ...
Repo update ...
Kind network found:
Metallb will be configured in Layer 2 mode with the range: 172.18.255.246 - 172.18.255.255
error: Could not create namespace for metallb: The connection to the server localhost:8080 was refused - did you specify the right host or port?
Aborted!

**Comment by Magi-Jakimovska** [comment]
@teodora-aleksovska, please list the action points to resolve the new issue. 
Thanks

**Comment by teodora-aleksovska** [comment]
@gocemitevski  please review this [PR](https://github.com/keitaroinc/enabler/pull/63).

My result after running _setup metallb --kube-context kind_: 

teodora@teodora-ThinkPad-T16-Gen-1:~/Project/enabler$ enabler setup metallb --kube-context kind 
Metallb not found. Installing...
Downloading metallb version ...
Repo update ...
Kind network found:
Metallb will be configured in Layer 2 mode with the range: 172.18.255.246 - 172.18.255.255
Created a namespace for metallb
✓ Metallb installed on cluster.

**Comment by JasminaPN** [comment]
closing since the MR was approved.
