### ISSUE TITLE
Sprint 3: Enabler - general

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#58]
The enabler app needs to be updated with the following:
- [x] licence file
- [x] meta data - pyproject.toml
- [x] unit tests

Reference - testing results from @Filip3mac ([#307](https://github.com/keitaroinc/getafix_internal-getafix-tasks/issues/307)):

- Enabler is currently missing a licence file.
- Enabler is missing some meta data like a pyproject.toml.

- No unit tests are found for this application.

**Comment by JasminaPN** [comment]
This sub-ticket will be moved to Sprint 4: Improvements.

**Comment by JasminaPN** [comment]
The unit tests were descoped for Sprint 3. A separate task will be opened for Sprint 4.
