### ISSUE TITLE
Sprint 4: Enabler kind cluster management

### ISSUE THREAD

**Issue by Magi-Jakimovska** [keitaroinc/enabler#64]
It would be a beneficial improvement to check the version of dependencies. For resolving issue [#57](https://github.com/orgs/keitaroinc/projects/309/views/1?pane=issue&itemId=53689193), we updated the Kind version from 0.7.0 to 0.22.0 Implementing a check for the version before initiating the download process would be advantageous.

**Comment by JasminaPN** [comment]
Closing since we are moving to Plane Task Board.
