### ISSUE TITLE
Sprint 4: Enabler - platform release

### ISSUE THREAD

**Issue by teodora-aleksovska** [keitaroinc/enabler#66]
After running enabler platform release i got this error:

teodora@teodora-ThinkPad-T16-Gen-1:~/Project/enabler$ enabler platform release
Usage: enabler platform release [OPTIONS] VERSION SUBMODULES REPOPATH
Try 'enabler platform release --help' for help.

Error: Missing argument 'VERSION'.

**Comment by JasminaPN** [comment]
Closing since we are moving to plane task Board.
