### ISSUE TITLE
Bug: Cannot install enabler with latest python version (3.12.4)

### ISSUE THREAD

**Issue by daemy** [keitaroinc/enabler#85]
Here is output from `pip install --editable .`

>  Obtaining file:///home/dimi/enabler
>   Installing build dependencies ... done
>   Checking if build backend supports build_editable ... done
>   Getting requirements to build editable ... done
>   Preparing editable metadata (pyproject.toml) ... done
> Collecting click==7.1.1 (from enabler_keitaro_inc==0.1.2)
>   Downloading click-7.1.1-py2.py3-none-any.whl.metadata (2.9 kB)
> Collecting click-log==0.3.2 (from enabler_keitaro_inc==0.1.2)
>   Downloading click_log-0.3.2-py2.py3-none-any.whl.metadata (1.3 kB)
> Collecting click-spinner==0.1.8 (from enabler_keitaro_inc==0.1.2)
>   Downloading click-spinner-0.1.8.tar.gz (18 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [31 lines of output]
>       /tmp/pip-install-sc652mrp/click-spinner_9098d8b91f594bd6a5071813f5ab798a/versioneer.py:485: SyntaxWarning: invalid escape sequence '\s'
>         LONG_VERSION_PY['git'] = '''
>       Traceback (most recent call last):
>         File "/home/dimi/enabler/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/dimi/enabler/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/dimi/enabler/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-rpcy47mh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=[])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-build-env-rpcy47mh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
>           self.run_setup()
>         File "/tmp/pip-build-env-rpcy47mh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 497, in run_setup
>           super().run_setup(setup_script=setup_script)
>         File "/tmp/pip-build-env-rpcy47mh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
>           exec(code, locals())
>         File "<string>", line 10, in <module>
>         File "/tmp/pip-install-sc652mrp/click-spinner_9098d8b91f594bd6a5071813f5ab798a/versioneer.py", line 1473, in get_version
>           return get_versions()["version"]
>                  ^^^^^^^^^^^^^^
>         File "/tmp/pip-install-sc652mrp/click-spinner_9098d8b91f594bd6a5071813f5ab798a/versioneer.py", line 1406, in get_versions
>           cfg = get_config_from_root(root)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/tmp/pip-install-sc652mrp/click-spinner_9098d8b91f594bd6a5071813f5ab798a/versioneer.py", line 412, in get_config_from_root
>           parser = configparser.SafeConfigParser()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.

As I did some basic research, SafeConfigParser has been renamed in Python 3.12 so that could potentially be the main issue here.

**Comment by gocemitevski** [comment]
Should be resolved with https://github.com/keitaroinc/enabler/pull/86.
