### ISSUE TITLE
Sprint 4: Add  documentation for project in README.md

### ISSUE THREAD

**Issue by InaKeitaro** [keitaroinc/enabler#9]
Create a README.me file including the following:

- information about the application, 
- instructions for installation, 
- guidance on how to use it, and 
- information on any relevant code changes/updates.

**Note:** The file is WIP and will be updated with any new code change. It'll be completed with Sprint 3 when all improvements to the application are tested and deployed.

**Comment by JasminaPN** [comment]
Closing since we are moving to Plane Task Board.
